# Generated by Django 5.2.7 on 2025-10-08 05:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilowatt_hours', models.DecimalField(decimal_places=3, max_digits=10)),
                ('current_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('current_ampere', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='meters.meter')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MeterSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(blank=True, max_length=100)),
                ('voltage', models.CharField(blank=True, max_length=100)),
                ('ampere', models.CharField(blank=True, max_length=100)),
                ('additional_specs', models.TextField(blank=True)),
                ('voltage_upper_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('voltage_lower_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ampere_upper_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ampere_lower_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('meter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='meters.meter')),
            ],
        ),
    ]
